version: '3'
services:
  db:
    image: 'postgres:14-alpine'
    env_file:
      - ./env/postgres.env
    # We use bind mounts so we can backup db data
    volumes:
      - ./db/data:/var/lib/postgresql/data
    # Open this port if you want to remote access through third party software (e.g DBeaver)
    #ports:
    #  - '5432:5432'
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d lportal -U liferay"]
      interval: 5s
      timeout: 5s
      retries: 5

  elasticsearch:
    #image: 'elasticsearch:7.17.2'
    build: 
      context: .
      dockerfile: ./dockerfiles/elasticsearch.dockerfile
    env_file:
      - ./env/elasticsearch.env
    # Open these ports if you want to remote access through third party software
    ports:
      - '9200:9200'
      - '9300:9300'
    #volumes:
    #  - elasticData:/usr/share/elasticsearch/data
    #  - elasticCerts:/usr/share/elasticsearch/config/certs

  liferay:
    image: 'liferay/portal:7.4.3.19-ga19'
    user: liferay
    env_file:
      - ./env/liferay.env
    volumes:
      - data:/opt/liferay/data
      - osgi:/opt/liferay/osgi
      - license:/opt/liferay/license
      - logs:/opt/liferay/logs
#       Can't use this bind mounts cause it changes folder ownership to root...
#      - ./liferay/data:/opt/liferay/data
#      - ./liferay/osgi:/opt/liferay/osgi
#      - ./liferay/license:/opt/liferay/license
#      - ./liferay/logs:/opt/liferay/logs
      - ./liferay/mnt:/mnt/liferay
      - ./liferay/scripts:/usr/local/liferay/scripts/
    ports:
     - '80:8080'
    depends_on:      
      db:
        condition: service_healthy



volumes:
  data:
  osgi:
  license:
  logs:
  elasticData:
  elasticCerts: